from .core import MsgBase, Registry
from .messages import (
    CClipboardMsg,
    CCloseMsg,
    CEnterMsg,
    CInfoAckMsg,
    CKeepAliveMsg,
    CLeaveMsg,
    CNoopMsg,
    CResetOptionsMsg,
    CScreenSaverMsg,
    DClipboardMsg,
    DDragInfoMsg,
    DFileTransferMsg,
    DInfoMsg,
    DKeyDownLangMsg,
    DKeyDownMsg,
    DKeyRepeatMsg,
    DKeyUpMsg,
    DLanguageSynchronisationMsg,
    DMouseDownMsg,
    DMouseMoveMsg,
    DMouseRelMoveMsg,
    DMouseUpMsg,
    DMouseWheelMsg,
    DSecureInputNotificationMsg,
    DSetOptionsMsg,
    EBadMsg,
    EBusyMsg,
    EIncompatibleMsg,
    EUnknownMsg,
    HelloBackMsg,
    HelloMsg,
    QInfoMsg,
)
from .parser import SynergyParser
from .protocol_types import MsgID
from .struct_types import (
    Double,
    DoubleComplex,
    FixedString,
    Float,
    Float16,
    FloatComplex,
    Int8,
    Int16,
    Int32,
    Int64,
    LInt32,
    SizeT,
    SSizeT,
    SString,
    String,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    ULInt32,
    VarString,
    XPad,
)

_core_exports = [Registry, MsgBase, SynergyParser, MsgID]

# 自动收集所有消息类（继承自 MsgBase）
_message_classes = [
    HelloMsg,
    HelloBackMsg,
    CCloseMsg,
    CEnterMsg,
    CLeaveMsg,
    CNoopMsg,
    CInfoAckMsg,
    CClipboardMsg,
    CScreenSaverMsg,
    CKeepAliveMsg,
    CResetOptionsMsg,
    DLanguageSynchronisationMsg,
    DSecureInputNotificationMsg,
    DKeyUpMsg,
    DInfoMsg,
    DKeyDownMsg,
    DKeyRepeatMsg,
    DMouseDownMsg,
    DMouseUpMsg,
    DKeyDownLangMsg,
    DMouseWheelMsg,
    DMouseMoveMsg,
    DMouseRelMoveMsg,
    DClipboardMsg,
    DDragInfoMsg,
    DSetOptionsMsg,
    DFileTransferMsg,
    QInfoMsg,
    EBadMsg,
    EUnknownMsg,
    EIncompatibleMsg,
    EBusyMsg,
]

_struct_types = [
    Double,
    DoubleComplex,
    FixedString,
    Float,
    Float16,
    FloatComplex,
    Int8,
    Int16,
    Int32,
    Int64,
    LInt32,
    SizeT,
    SSizeT,
    SString,
    String,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    ULInt32,
    VarString,
    XPad,
]

__all__ = _core_exports + _message_classes + _struct_types
